DROP DATABASE IF EXISTS qa;
CREATE DATABASE qa;

\c qa

CREATE TABLE IF NOT EXISTS questions(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  body text NOT NULL,
  date bigint,
  name text NOT NULL,
  email text NOT NULL,
  reported boolean DEFAULT FALSE,
  helpfulness integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS answers(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id integer NOT NULL REFERENCES questions ON DELETE CASCADE,
  body text NOT NULL,
  date bigint,
  name text NOT NULL,
  email text NOT NULL,
  reported boolean DEFAULT FALSE,
  helpfulness integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS answers_photos(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id integer NOT NULL REFERENCES answers ON DELETE CASCADE,
  url text NOT NULL
);

COPY questions (id, product_id, body, date, name, email, reported, helpfulness)
  FROM '/data/questions.csv'
  WITH CSV HEADER;

COPY answers (id, question_id, body, date, name, email, reported, helpfulness)
  FROM '/data/answers.csv'
  WITH CSV HEADER;

COPY answers_photos (id, answer_id, url)
  FROM '/data/answers_photos.csv'
  WITH CSV HEADER;

ALTER TABLE questions
  ADD CONSTRAINT question_body_length CHECK (length(body) <= 1e4),
  ADD CONSTRAINT question_name_length CHECK (length(name) <= 1e2),
  ADD CONSTRAINT question_email_length CHECK (length(email) <= 1e2),
  ALTER COLUMN date TYPE timestamp(3) with time zone
    USING to_timestamp(date / 1000.0),
  ALTER COLUMN date SET DEFAULT CURRENT_TIMESTAMP(3);

SELECT setval('questions_id_seq', (SELECT max(id) FROM questions));

ALTER TABLE answers
  ADD CONSTRAINT answer_body_length CHECK (length(body) <= 1e4),
  ADD CONSTRAINT answer_name_length CHECK (length(name) <= 1e2),
  ADD CONSTRAINT answer_email_length CHECK (length(email) <= 1e2),
  ALTER COLUMN date TYPE timestamp(3) with time zone
    USING to_timestamp(date / 1000.0),
  ALTER COLUMN date SET DEFAULT CURRENT_TIMESTAMP(3);

SELECT setval('answers_id_seq', (SELECT max(id) FROM answers));

SELECT setval('answers_photos_id_seq', (SELECT max(id) FROM answers_photos));

CREATE INDEX questions_product_id_index ON questions (product_id);
CREATE INDEX questions_date_index ON questions (date DESC);
CREATE INDEX answers_question_id_index ON answers (question_id);
CREATE INDEX answers_date_index ON answers (date DESC);
CREATE INDEX answers_photos_answer_id_index ON answers_photos (answer_id);
