const { Pool, Client } = require('pg');

module.exports = async () => {
  const client = new Client({
    database: 'template1',
  });

  try {
    await client.connect();
    await client.query(`DROP DATABASE IF EXISTS ${process.env.PGDATABASE};`);
    await client.query(`CREATE DATABASE ${process.env.PGDATABASE};`);
    await client.end();
    console.log(`Database ${process.env.PGDATABASE} created.`);

    const pool = new Pool();

    await pool.query(`
      CREATE TABLE IF NOT EXISTS questions(
        question_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id integer NOT NULL,
        question_body text NOT NULL,
        question_date bigint,
        asker_name text NOT NULL,
        asker_email text NOT NULL,
        reported boolean DEFAULT FALSE,
        question_helpfulness integer DEFAULT 0
      );

      CREATE TABLE IF NOT EXISTS answers(
        answer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        question_id integer NOT NULL REFERENCES questions ON DELETE CASCADE,
        body text NOT NULL,
        date bigint,
        answerer_name text NOT NULL,
        answerer_email text NOT NULL,
        reported boolean DEFAULT FALSE,
        helpfulness integer DEFAULT 0
      );

      CREATE TABLE IF NOT EXISTS answers_photos(
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        answer_id integer  NOT NULL REFERENCES answers ON DELETE CASCADE,
        url text NOT NULL
      );
    `);
    console.log('Tables questions, answers, and answers_photos created.');

    await Promise.all([
      await pool.query(`
        COPY questions (question_id, product_id, question_body, question_date, asker_name, asker_email, reported, question_helpfulness)
          FROM '${process.env.DBPATH}/questions.csv'
          WITH CSV HEADER;
      `),
      await pool.query(`
        COPY answers (answer_id, question_id, body, date, answerer_name, answerer_email, reported, helpfulness)
          FROM '${process.env.DBPATH}/answers.csv'
          WITH CSV HEADER;
      `),
      await pool.query(`
        COPY answers_photos (id, answer_id, url)
          FROM '${process.env.DBPATH}/answers_photos.csv'
          WITH CSV HEADER;
      `),
    ]);
    console.log('Tables questions, answers, and answers_photos populated.');

    await pool.query(`
      ALTER TABLE questions
        ADD CONSTRAINT question_body_length CHECK (length(question_body) <= 1e4),
        ADD CONSTRAINT asker_name_length CHECK (length(asker_name) <= 1e2),
        ADD CONSTRAINT asker_email_length CHECK (length(asker_email) <= 1e2),
        ALTER COLUMN question_date TYPE timestamp(3)
          USING to_timestamp(question_date / 1000.0),
        ALTER COLUMN question_date SET DEFAULT LOCALTIMESTAMP(3);

      ALTER TABLE answers
        ADD CONSTRAINT answer_body_length CHECK (length(body) <= 1e4),
        ADD CONSTRAINT answerer_name_length CHECK (length(answerer_name) <= 1e2),
        ADD CONSTRAINT answerer_email_length CHECK (length(answerer_email) <= 1e2),
        ALTER COLUMN date TYPE timestamp(3)
          USING to_timestamp(date / 1000.0),
        ALTER COLUMN date SET DEFAULT LOCALTIMESTAMP(3);

      CREATE INDEX questions_product_id_index ON questions (product_id);
      CREATE INDEX questions_date_index ON questions (question_date DESC);
      CREATE INDEX answers_question_id_index ON answers (question_id);
      CREATE INDEX answers_date_index ON answers (date DESC);
      CREATE INDEX answers_photos_answer_id_index ON answers_photos (answer_id);
      `);
    console.log(
      'Constraints placed on tables questions and answers.\nColumns questions.question_date and answers.date converted to type timestamp.\nIndexes created on ids and dates.',
    );
  } catch (error) {
    console.log(`Failed to create database ${process.env.PGDATABASE}:`, error);
  }
};
